_target_: base_ddpm_training.NoiseScheduler
name: DDIM
beta_schedule: squaredcos_cap_v2
inference_timesteps: 100
dynamic_thresholding: True
num_train_timesteps: 1000
beta_start: 0.0001
beta_end: 0.01
