wandb:
  project_name: ddpm_training
  name: text_guided
clip_model_name: "ViT-B-32"
prompt: nine

defaults:
  - dataset: mnist
  - noise_scheduler: ddpm
  - noise_scheduler_sample: ddim

seed: 42
exp_lr_schedule: 0.91
batch_size: 10
num_workers: 2
guidance_rate: 0
device: cuda
lr: 1.0e-3
n_epochs: 10
log_samples_every: 300
grad_accumulation_steps: 4
